---
title: "Initial dataset cleaning"
output: html_notebook
---

```{r}
# Load necessary packages
library(dplyr)
```


```{r}
# Setting up and checking data frame
df <- read.csv("/Users/thomassimmons/c/p/data/SDUD-2024.csv")
head(df)
```

```{r}
# Number of columns
ncol(df)
```

```{r}
na_rows <- which(rowSums(is.na(df)) > 0)
df[na_rows, ]
```
```{r}
# Version with all na values removed
df_clean <- na.omit(df)
```

```{r}
# Export clean csv
write.csv(df_clean, file = "df_clean.csv", row.names = FALSE)
```

```{r}
dim(df_clean)
```

```{r}
colnames(df_clean)
```

```{r}
summary(df_clean)
```

```{r}
# No more null values
colSums(is.na(df_clean))
```
```{r}
# Check how many rows have suppression
table(df_clean$`Suppression.Used`)

# Filter suppressed rows
suppressed <- df %>% filter(`Suppression.Used` == TRUE)

# Filter non-suppressed rows
not_suppressed <- df %>% filter(`Suppression.Used` == FALSE)
```

```{r}
colnames(df_clean) <- colnames(df_clean) |>
  tolower() |>
  gsub("\\.", "_", x = _)
```

```{r}
colnames(df_clean)
```

